  name: Calculate Carbon
  
  on: workflow_dispatch
        
  jobs:
    carbon-measure:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-go@v3
          with:
            go-version: 1.17
        - name: Set and check goenv
          run: |
              go env -w GO111MODULE=on
              go version && go env
        - id: carbon_output
          # uses: ./src/carbon-measure-action
          # uses: Green-Software-Foundation/Carbon_CI_Pipeline_Tooling@Dev
          uses: devidayal22/GSFGO@Dev 
          with:
            IACFile: $GITHUB_WORKSPACE/data/azuredeploy.json
            IACType: arm
            CloudProvider: azure
            CARBON_RATE_PROVIDER: watttime
          env:
            ELECTRICITY_MAP_AUTH_TOKEN: ${{ secrets.ELECTRICITY_MAP_AUTH_TOKEN }}
            WATT_TIME_USER: devidayal
            WATT_TIME_PASS: aarvi@1234
            body: |
             pounds carbon equivalent per MWh = ${{ steps.carbon_output.outputs.grams_carbon_equivalent_per_kwh }}
             pounds co2 emitted over 24h = ${{ steps.carbon_output.outputs.grams_emitted_over_24h }}
             reactions: rocket
          
        # - name: Create comment
        #   uses: peter-evans/create-or-update-comment@v2
        #   with:
        #     issue-number: ${{ github.event.pull_request.number }}
        #     body: |
        #       pounds carbon equivalent per MWh = ${{ steps.carbon_output.outputs.grams_carbon_equivalent_per_kwh }}
        #       pounds co2 emitted over 24h = ${{ steps.carbon_output.outputs.grams_emitted_over_24h }}
        #     reactions: rocket
        
        
    

